# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2af1cbf75fd33a80b7912a5c4a5d2be024256456703f3996ba6b15447d759dc45baafae7d5803edc10137abb7f0f3c1261246f7575566537b20820a7fb317aed

test:
  secret_key_base: b4549a6413140b04a1b6923aa84b02abe76bbefff7d4d4d592ab168e6adaf70577b45795c3b2efca50bf6860b435263eba99be26f7f492ae90d0db9692b594fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
